// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4PcRjeyrvnSZIytbfe12KQ0Ks-KteUzs',
    appId: '1:491106109201:web:94bf538210ec659f65aeb0',
    messagingSenderId: '491106109201',
    projectId: 'agendawa-5d8a1',
    authDomain: 'agendawa-5d8a1.firebaseapp.com',
    storageBucket: 'agendawa-5d8a1.firebasestorage.app',
    measurementId: 'G-V6JMLV2XKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3VUi6IphkLdKFvecSUcolCd-6mF5Exog',
    appId: '1:491106109201:android:a2fa863d9be6a77365aeb0',
    messagingSenderId: '491106109201',
    projectId: 'agendawa-5d8a1',
    storageBucket: 'agendawa-5d8a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGEFEUJxgn1xaorlWrW-DlTS8ZE1MqkCQ',
    appId: '1:491106109201:ios:8f02a96cadd04e2365aeb0',
    messagingSenderId: '491106109201',
    projectId: 'agendawa-5d8a1',
    storageBucket: 'agendawa-5d8a1.firebasestorage.app',
    iosBundleId: 'com.example.agendaWa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGEFEUJxgn1xaorlWrW-DlTS8ZE1MqkCQ',
    appId: '1:491106109201:ios:8f02a96cadd04e2365aeb0',
    messagingSenderId: '491106109201',
    projectId: 'agendawa-5d8a1',
    storageBucket: 'agendawa-5d8a1.firebasestorage.app',
    iosBundleId: 'com.example.agendaWa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4PcRjeyrvnSZIytbfe12KQ0Ks-KteUzs',
    appId: '1:491106109201:web:a406fde0df87bb2365aeb0',
    messagingSenderId: '491106109201',
    projectId: 'agendawa-5d8a1',
    authDomain: 'agendawa-5d8a1.firebaseapp.com',
    storageBucket: 'agendawa-5d8a1.firebasestorage.app',
    measurementId: 'G-1P4CJS82RD',
  );

}